=== Lokankara/XML-mapper/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://dom.com.java.xml.parser/entity"
	xmlns:tns="http://dom.com.java.xml.parser/entity">

	<element name="Cars">
		<complexType>
			<sequence>
				<element name="Car" type="tns:Car" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Car">
		<sequence>
			<element name="Model" type="token" />
			<element name="Color" type="token" />
			<element name="Wheel" type="tns:Wheel" />
			<element name="Engine" type="tns:Engine" />
			<element name="Type" type="tns:Type" />
			<element name="Price">
				<simpleType>
					<restriction base="decimal">
						<fractionDigits value="2"/>
						<totalDigits value="4"/>
						<minExclusive value="0"/>
					</restriction>
				</simpleType>
			</element>
		</sequence>
		<attribute name="Brand" type="tns:Brand" use="optional" />
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="int">
					<minExclusive value="0"/>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="Type">
		<restriction base="token">
			<enumeration value="gasoline"/>
			<enumeration value="nuclear"/>
			<enumeration value="electricity"/>
			<pattern value="gasoline|nuclear|electricity" />
		</restriction>
	</simpleType>

	<simpleType name="Brand">
		<restriction base="token">
			<pattern value="Audi|BMW|Toyota|Kia" />
		</restriction>
	</simpleType>

	<complexType name="Wheel">
		<sequence>
			<element name="Tire" type="token" />

			<element name="Position">
				<simpleType>
					<restriction base="token">
						<minLength value="3"/>
						<maxLength value="10"/>
					</restriction>
				</simpleType>
			</element>

			<element name="Diameter">
				<simpleType>
					<restriction base="int">
						<minExclusive value="0" />
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>

	<complexType name="Engine">
		<all>
			<element name="Power" minOccurs="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
						<maxInclusive value="60" />
					</restriction>
				</simpleType>
			</element>

			<element name="Run" type="boolean" minOccurs="0"/>

			<element name="Fuel" minOccurs="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
					</restriction>
				</simpleType>
			</element>
		</all>
	</complexType>
</schema>

=== Lokankara/XML-mapper/input.xml
<?xml version="1.1" encoding="UTF-8"?>
<tns:Cars
		xmlns:tns="http://dom.com.java.xml.parser/entity"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://dom.com.java.xml.parser/entity input.xsd">

	<Car id="1" Brand="Audi">
		<Model>A3</Model>
		<Color>Silver</Color>
		<Wheel>
			<Tire>Summer</Tire>
			<Position>Front</Position>
			<Diameter>22</Diameter>
		</Wheel>
		<Engine>
			<Power>20</Power>
			<Fuel>80</Fuel>
			<Run>true</Run>
		</Engine>
		<Type>electricity</Type>
		<Price>15.59</Price>
	</Car>

	<Car id="2" Brand="Toyota">
		<Model>C-HR</Model>
		<Color>White</Color>
		<Wheel>
			<Tire>Winter</Tire>
			<Position>Rear</Position>
			<Diameter>22</Diameter>
		</Wheel>
		<Engine>
			<Power>27</Power>
			<Fuel>105</Fuel>
			<Run>false</Run>
		</Engine>
		<Type>electricity</Type>
		<Price>12.79</Price>
	</Car>

	<Car id="3" Brand="BMW">
		<Model>X5</Model>
		<Color>Red</Color>
		<Wheel>
			<Tire>Winter</Tire>
			<Position>Front</Position>
			<Diameter>22</Diameter>
		</Wheel>
		<Engine>
			<Fuel>60</Fuel>
			<Power>22</Power>
			<Run>true</Run>
		</Engine>
		<Type>nuclear</Type>
		<Price>16.49</Price>
	</Car>

	<Car id="4" Brand="Kia">
		<Model>SportAge</Model>
		<Color>Violet</Color>
		<Wheel>
			<Tire>Summer</Tire>
			<Position>Front</Position>
			<Diameter>24</Diameter>
		</Wheel>
		<Engine>
			<Fuel>60</Fuel>
			<Power>22</Power>
			<Run>true</Run>
		</Engine>
		<Type>gasoline</Type>
		<Price>20.99</Price>
	</Car>

	<Car id="5" Brand="BMW">
		<Model>X6</Model>
		<Color>Green</Color>
		<Wheel>
			<Tire>Winter</Tire>
			<Position>Rear</Position>
			<Diameter>24</Diameter>
		</Wheel>
		<Engine>
			<Fuel>60</Fuel>
			<Power>22</Power>
			<Run>true</Run>
		</Engine>
		<Type>gasoline</Type>
		<Price>20.99</Price>
	</Car>
</tns:Cars>

=== Lokankara/XML-mapper/output.dom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dom.com.java.xml.parser/entity input.xsd" xmlns:tns="http://dom.com.java.xml.parser/entity">
    <Car Brand="Audi" id="1">
        <Model>A3</Model>
        <Color>Silver</Color>
        <Wheel>
            <Tire>Summer</Tire>
            <Position>Front</Position>
            <Diameter>22</Diameter>
        </Wheel>
        <Engine>
            <Power>20</Power>
            <Run>true</Run>
            <Fuel>80</Fuel>
        </Engine>
        <Type>electricity</Type>
        <Price>15.59</Price>
    </Car>
    <Car Brand="Toyota" id="2">
        <Model>C-HR</Model>
        <Color>White</Color>
        <Wheel>
            <Tire>Winter</Tire>
            <Position>Rear</Position>
            <Diameter>22</Diameter>
        </Wheel>
        <Engine>
            <Power>27</Power>
            <Run>false</Run>
            <Fuel>105</Fuel>
        </Engine>
        <Type>electricity</Type>
        <Price>12.79</Price>
    </Car>
    <Car Brand="Kia" id="4">
        <Model>SportAge</Model>
        <Color>Violet</Color>
        <Wheel>
            <Tire>Summer</Tire>
            <Position>Front</Position>
            <Diameter>24</Diameter>
        </Wheel>
        <Engine>
            <Power>22</Power>
            <Run>true</Run>
            <Fuel>60</Fuel>
        </Engine>
        <Type>gasoline</Type>
        <Price>20.99</Price>
    </Car>
    <Car Brand="BMW" id="5">
        <Model>X6</Model>
        <Color>Green</Color>
        <Wheel>
            <Tire>Winter</Tire>
            <Position>Rear</Position>
            <Diameter>24</Diameter>
        </Wheel>
        <Engine>
            <Power>22</Power>
            <Run>true</Run>
            <Fuel>60</Fuel>
        </Engine>
        <Type>gasoline</Type>
        <Price>20.99</Price>
    </Car>
    <Car Brand="BMW" id="3">
        <Model>X5</Model>
        <Color>Red</Color>
        <Wheel>
            <Tire>Winter</Tire>
            <Position>Front</Position>
            <Diameter>22</Diameter>
        </Wheel>
        <Engine>
            <Power>22</Power>
            <Run>true</Run>
            <Fuel>60</Fuel>
        </Engine>
        <Type>nuclear</Type>
        <Price>16.49</Price>
    </Car>
</tns:Cars>
